input_list = tk_1(4)
print("input numbers:", input_list)
min_max = tk_2(input_list)
print("min and max numbers:", min_max)
div_list = tk_3(input_list)
print("list divided by average:", div_list)
mul_list = tk_4(input_list)
print("list multiply by average:", mul_list)
square_list = tk_5(input_list)
print("square root list:", square_list)
